image: gitpod/workspace-full-vnc
ports:
- port: 6080
tasks:
- init: pip3 install Cython pygame cyrandom
- command: ./build.sh

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults eto false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false